### PR TITLE
AWS Seoul region support

### PR DESCRIPTION
**Pull request by zeliard**
[add] ap-northeast-2 region

### CODE REVIEW

**Comment by JonathanHenson** [comment]
Wow..... that was quick.... You need to update the Region.h and Region.cpp
file in core and then update the endpoint computation in the generator.
Most of those files you manually updated are generated, so the fix needs to
happen there.

Thanks for your work on this.

**Comment by zeliard** [comment]
Yep! just fixed RegionEndpointMapper.java
Thanks for adding AWS Seoud region :+1:

**Comment by JonathanHenson** [comment]
can you shoot me a pull request without the updates to the clients? I just need the client generator update and the region.h and region.cpp updates.

**Comment by JonathanHenson** [comment]
b.t.w. you can use endpoint override and authenticationRegion in the client config anytime you need a region we haven't explicitly called out.

**Comment by zeliard** [comment]
OK, I fixed this PR in the contribution guidelines.
3 files (region.h, region,cpp, and regionendpointmapper.java) are changed eventually.

**Comment by JonathanHenson** [comment]
One last thing. Could you rebase this into one commit?

**Comment by zeliard** [comment]
done. 
(but your last commit (contribution guidelines) has been included while squashing my commits)
anyway, thanks for your kindness.

**Pull request merged**
